[workspace]
authors = ["Belize GEO <eac0021@uah.edu>"]
channels = ["conda-forge"]
name = "Homework_2"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.2.0,<8"
pip = ">=26.0.1,<27"
matplotlib = ">=3.10.8,<4"
geopandas = ">=1.1.2,<2"
